### ISSUE TITLE
Assertion `ssim > 0' fails for Images <= 15 pixel wide or high

### ISSUE THREAD

**Issue by rcanavan** [pornel/dssim#29] opened 2016-08-03 17:17 UTC
When used with any image with width or height less than or equal to 15, dssim fails with an Assertion:

```
dssim: src/dssim.c:668: to_dssim: Assertion `ssim > 0' failed.
Aborted (core dumped)
```

**Comment by pornel** [comment] 2016-08-03 17:58
Can you attach an example image? What platform are you running on?

**Comment by rcanavan** [comment] 2016-08-03 19:25
I'm using Ubuntu 16.04 with 1.2.54-1ubuntu1. The test images were generated with xv and imagemagick and re-scaled to various sizes using @convert -resize ??x??.
15x15:  ![a](https://cloud.githubusercontent.com/assets/4719149/17378982/8d766a26-59c0-11e6-9e2f-cdda8fa0d2e6.png) ![b](https://cloud.githubusercontent.com/assets/4719149/17378986/902466d8-59c0-11e6-88cd-19e15bf1ee39.png)

1x1: ![x](https://cloud.githubusercontent.com/assets/4719149/17379015/b5fc652c-59c0-11e6-8b98-21151f122d51.png) ![y](https://cloud.githubusercontent.com/assets/4719149/17379020/b9209c8c-59c0-11e6-8f9c-735da02220f4.png)

**Comment by pornel** [comment] 2016-08-04 18:50
Unfortunately, I'm unable to reproduce it. I've tried these images on 2f4946b615667ef057da46d7915757fba556e064 compiled for Debian 8.5 and OS X 10.11.

```sh
$ ./bin/dssim b5fc652c-59c0-11e6-8b98-21151f122d51.png b9209c8c-59c0-11e6-8f9c-735da02220f4.png
0.00000000  b9209c8c-59c0-11e6-8f9c-735da02220f4.png
$ ./bin/dssim 902466d8-59c0-11e6-88cd-19e15bf1ee39.png 8d766a26-59c0-11e6-9e2f-cdda8fa0d2e6.png
0.00000000  8d766a26-59c0-11e6-9e2f-cdda8fa0d2e6.png
```

**Comment by pornel** [comment] 2016-08-04 18:51
oh wait, nevermind. I forgot to enable debugging :)

**Comment by pornel** [comment] 2017-03-11 14:03
Probably fixed in 4f9b12106e35bb3f1b9382dd064dece3a3f3f365

**Closed by pornel** 2017-03-11 14:03 UTC

**Comment by rcanavan** [comment] 2017-03-13 17:55
Fixes the crash, but dssim when comparing an image with a single black pixel and an image with a single white pixel is 0.00000000. I've also tested a 2x2 black and white checkerboard against its inverse or a red and green checkerboard - both return 0.00000000. That doesn't seem right.


```
convert xc:black b.png
convert xc:white w.png
dssim  b.png  w.png
0.00000000      w.png
```

**Comment by pornel** [comment] 2017-03-13 18:23
SSIM is not meaningful for single pixel. This implementation uses blur, so it's also useless for sizes smaller than the blur radius. Try with at least 8x8 pixels.
