### ISSUE TITLE
assert() fails

### ISSUE THREAD

**Issue by doublex** [pornel/dssim#37] opened 2017-01-19 11:27 UTC
`assert(ssim > 0);` in `to_dssim()` fails.

Commandline:
`bin/dssim /tmp/crash-original.png  /tmp/crash-modified.png`
![crash-modified](https://cloud.githubusercontent.com/assets/274624/22105087/ae8ec81e-de42-11e6-846e-61538f3fd350.png)
![crash-original](https://cloud.githubusercontent.com/assets/274624/22105088/ae8ee5ce-de42-11e6-8dff-05d4d12673e0.png)

**Comment by filex** [comment] 2017-01-19 17:25
This is probably a duplicate of #29 because one side of the image is smaller than 16px.

**Comment by pornel** [comment] 2017-11-10 16:52
Please try v2.8.0 1e4760418c1b8a47a26b325d1e28761e46cd9522

**Closed by pornel** 2017-11-10 16:52 UTC
